insert into onlinestore.product (id, name, price, amount, description, type_id) values (1, 'Fender Squier MM Strat HT Black', 3892, 8, 'Очень хорошая гитара', 3);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (2, 'AXL Badwater SRO AS820', 4684, 23, 'Очень хорошая гитара', 3);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (3, 'Fender Squier Bullet Stratocaster', 5560, 3, 'Очень хорошая гитара', 3);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (4, 'Ibanez GRG170DX BKN', 8788, 9, 'Очень хорошая гитара', 3);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (5, 'Fender Squier Contemporary Stratocaster HH MN', 9922, 4, 'Очень хорошая гитара', 3);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (6, 'Ibanez JS2480 MCR (226864) Muscle', 60952, 6, 'Очень хорошая гитара', 3);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (7, 'Jackson SL4X Soloist RW', 17577, 13, 'Очень хорошая гитара', 3);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (8, 'Fender American Original 60s Tele RW 3-Tone', 52448, 3, 'Очень хорошая гитара', 3);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (9, 'Alfabeto CL44 NT', 2195, 45, 'Очень хорошая гитара', 1);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (10, 'Bandes CG-851C RD', 1691, 53, 'Очень хорошая гитара', 1);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (11, 'VALENCIA VC304CE', 3530, 25, 'Очень хорошая гитара', 1);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (12, 'Admira Paloma', 5347, 18, 'Очень хорошая гитара', 1);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (13, 'Admira Diana', 5152, 13, 'Очень хорошая гитара', 1);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (14, 'Cort Action DLX Plus', 7700, 9, 'Очень хорошая гитара', 2);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (15, 'Cort Action Plus', 5670, 19, 'Очень хорошая гитара', 2);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (16, 'Parksons SPB-140 TBLB', 3591, 16, 'Очень хорошая гитара', 2);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (17, 'Cort GB-14PJ', 5950, 31, 'Очень хорошая гитара', 2);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (18, 'Cort Action DLX Plus Faded', 7700, 2, 'Очень хорошая гитара', 2);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (19, 'Parksons JB4111 Sunburst', 2099, 7, 'Очень хорошая гитара', 4);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (20, 'Trembita D/SS ST', 3530, 20, 'Очень хорошая гитара', 4);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (21, 'Alfabeto Solid AMS40 NT', 4284, 22, 'Очень хорошая гитара', 4);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (22, 'LAG TIKI TKT8 / travel', 3465, 9, 'Очень хорошая гитара', 4);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (23, 'Taylor 214CE-CF DLX', 45484, 3, 'Очень хорошая гитара', 5);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (24, 'Cort SFX-Dao Natural Gloss', 5810, 6, 'Очень хорошая гитара', 5);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (25, 'Tyma V-3 Plume', 6888, 4, 'Очень хорошая гитара', 5);
insert into onlinestore.product (id, name, price, amount, description, type_id) values (26, 'SX SD204CE', 14050, 17, 'Очень хорошая гитара', 5);
